# Generated by Django 4.0.3 on 2022-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
