# Generated by Django 4.0.3 on 2022-03-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
