# Generated by Django 4.0.3 on 2022-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('jobs', '0003_milestone_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.AlterField(
            model_name='job',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='job', to='milestones.milestone'),
        ),
    ]
