# Generated by Django 4.0.3 on 2022-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_milestone_alter_job_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
