# Generated by Django 4.0.3 on 2022-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='job_applicants', to='jobs.job'),
        ),
    ]
