# Generated by Django 4.0.3 on 2022-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_applied_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
