# Generated by Django 4.0.3 on 2022-03-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_city_user_country_user_job_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
