# Generated by Django 4.0.3 on 2022-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_rename_post_code_user_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
