# Generated by Django 4.0.3 on 2022-03-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_user_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
    ]
