# Generated by Django 4.0.3 on 2022-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('due_date', models.DateTimeField(default=None)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
