# Generated by Django 4.0.3 on 2022-03-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['due_date', 'pk']},
        ),
    ]
