# Generated by Django 4.0.3 on 2022-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=500)),
                ('logo', models.TextField(default=None, max_length=500)),
                ('website', models.CharField(default=None, max_length=200)),
                ('country', models.CharField(default=None, max_length=200)),
                ('sector', models.ManyToManyField(blank=True, related_name='company', to='sectors.sector')),
            ],
        ),
    ]
