# Generated by Django 4.0.3 on 2022-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_country_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
