# Generated by Django 4.0.3 on 2022-03-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=None, max_length=50)),
                ('start_year', models.DateField(default=None)),
                ('end_year', models.DateField(default=None)),
                ('company_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_employees', to='companies.company')),
            ],
        ),
    ]
